
version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/Api.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet build src/Api.sln
      - echo publish release
      - dotnet publish -c release -o ./out Api.sln
artifacts:
  files:
    - ./**/*
  base-directory: './out'      