version: "3.1"
services:
  mysqlsrv:
    image: mysql:5.7
    command: --lower_case_table_names=1
    container_name: MySql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "13467900"
      MYSQL_DATABASE: "dbApi"
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/mysql
  adminer:
    image: adminer
    ports: 
      - 8080:8080
    networks:
      - my-network
  api.application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.application
    environment:
      PORT: 5000
      LANDSCAPE: "br"
      APPLICATION_NAME: "api.application"
      VERSION: "1.0.0"
      CONFIG_VERSION: "1.0.0"
      CONFIG_ENVIRONMENT: "development"
      LOG_LEVEL: "INFORMATION"
      LOG_FORMAT: "JSON"
      MYSQL_CONNECTION: "Server=mysqlsrv;Port=3306;Uid=root;Pwd=13467900;Database=dbApi"
      MYSQL_DATABASE: "dbApi"
      MYSQL_VERSION: "5.7.30"
      MIGRATION: "APPLY"
    ports:
      - "5000:80"
    networks:
      - my-network
    depends_on:
      - "mysqlsrv"
networks:
  my-network:
    driver: bridge
volumes:
  db-volume:
