name: CI-CD Api

on:
  push:
    branches: ["master"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout..
      - uses: actions/checkout@v3.1.0
      
      - name: Criação da imagem docker
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thiagoalcantara/ci-cd-teste:v1
